# Generated by Django 4.1 on 2023-05-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="isactive",
            field=models.BooleanField(default=True),
        ),
    ]
